# configuration
variable "compute_compartment_ocid" {}
variable "ssh_public_key" {}
variable "compute_shape" {}
variable "compute_shape_config_memory_in_gbs" {}
variable "compute_shape_config_ocpus" {}
variable "region" {}
variable "tf_generated_ssh_key_pub" {}
variable "tf_generated_ssh_key" {}
variable "backend_port" {}
variable "computes_load_balanced" {}
variable "computes_load_balanced_and_load_balancer" {}
variable "deploy_load_balancer" {}
variable "instance_pool_node_count_initial" {}
variable "image_ocid" {}
variable "mount_target_private_ip" {}
variable "fss_export_path" {}
variable "deploy_fss" {}
variable "enable_is_bootstrapped_fss" {}
variable "enable_is_bootstrapped_http_server" {}
variable "http_app_tar_file_url" {}
variable "enable_is_bootstrapped_ssh_key" {}
variable "enable_is_bootstrapped_vnc_server" {}
variable "vncpasswd" {}
variable "computes_pool_specs" {}
variable "computes_solo_specs" {}
variable "lb_display_names_and_ocids" {}
variable "subnet_display_names_and_ocids" {}
# naming convention
variable "region_key" {}
variable "ad_name" {}
variable "fd_names" {}
variable "compute_collective_specs" {}
variable "instance_configuration" {}
variable "compute_instance" {}
variable "subnet" {}
variable "load_balancer" {}
variable "load_balancer_backend_set" {}
variable "instance_pool" {}